scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus - self-scrape'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cart - app-scrape'
    scrape_interval: 15s
    static_configs:
      - targets:
          - "cart:8080"

  - job_name: 'loms - app-scrape'
    scrape_interval: 15s
    static_configs:
      - targets:
          - "loms:8080"
